### ISSUE TITLE
Minor layout improvements

### ISSUE THREAD

**Issue by andys8** [oakesja/elm-news#11]
Hi @oakesja, 

elm news is a great project, that I'm using on a regular basis and want to thank you for.

May I suggest minor changes to the UI?

1. The icon is sometimes active/focussed and has a border, sometimes not. I'd remove it.
2. The text elm news could look better if aligned to the left. (Not sure)
3. The GitHub and Twitter logo would look better being smaller and having the same size.
4. GitHub logo in the footer looks also a bit to large on mobile.

![screenshot_20180409-112355](https://user-images.githubusercontent.com/13085980/38490327-146b5170-3be9-11e8-8562-15804ce0d76d.png)

These proposed changes are very subjective. I'd like to hear your opinion. If I find the time I could try to help you with the changes.

**Comment by oakesja** [comment]
Hey @andys8, thanks for the kind words. I agree with all of your observations. For the active/focus, please keep #7 and #8 in mind. I would welcome any PRs for these changes :)

**Comment by andys8** [comment]
Looking good
