### ISSUE TITLE
Broken layout "nbsp"

### ISSUE THREAD

**Issue by andys8** [oakesja/elm-news#17]
I saw this weird string (looking like a broken non breaking space) recently. The error appeared at the same call. It was reproducible when reloading the page.

![Screenshot_20190508-091911](https://user-images.githubusercontent.com/13085980/57357120-83071280-7172-11e9-9424-b389cc775ea7.png)
![Screenshot_20190508-091935](https://user-images.githubusercontent.com/13085980/57357129-87333000-7172-11e9-8032-d06606139bf8.png)

**Comment by oakesja** [comment]
@andys8 thank you for reporting this! It should be fixed now.
