### ISSUE TITLE
HTML Ampersand

### ISSUE THREAD

**Issue by andys8** [oakesja/elm-news#18]
There is currently an article by noredink which contains "&amp;". It should be "&".

![Screenshot_20190804-152253](https://user-images.githubusercontent.com/13085980/62424204-fcf45c80-b6cb-11e9-8ae1-1b422ab3dde2.png)
![Screenshot_20190804-152236](https://user-images.githubusercontent.com/13085980/62424205-fd8cf300-b6cb-11e9-80a9-801a77af0212.png)

**Comment by oakesja** [comment]
Thank you @andys8 for reporting this. It should be fixed now.

**Comment by andys8** [comment]
Another approach to avoid `innerHtml` could be a replacement. There is this package, but I found it just now.

https://package.elm-lang.org/packages/marcosh/elm-html-to-unicode/latest/

**Comment by oakesja** [comment]
I am open to PRs
