### ISSUE TITLE
Click behavior

### ISSUE THREAD

**Issue by gdotdesign** [oakesja/elm-news#3]
I suggest removing `preventDefault` https://github.com/oakesja/elm-news/blob/master/src/Analytics.elm#L84 from links because it breaks how normal users use them.

For example I always open links like these with the middle mouse button (wheel) click, this way the current page is still open but the target link is opened in a new window. Preventing default behavior will disable this feature.

**Comment by oakesja** [comment]
@gdotdesign Thank you for creating issue for this and #2. They are both related and now have been fixed
