### ISSUE TITLE
Red error messages are shown when clicking any news link in Firefox

### ISSUE THREAD

**Issue by lydell** [oakesja/elm-news#5]
This is what I get immediately after clicking the first news item, but before the site has loaded:

![screenshot from 2017-02-21 20-24-19](https://cloud.githubusercontent.com/assets/2142817/23181062/c863e8c8-f873-11e6-8028-21d8272348d6.png)

I can reproduce this consistently in Firefox, but never in Chrome.

**Comment by oakesja** [comment]
@lydell Thanks for reporting this issue! It should be fixed now.

**Comment by lydell** [comment]
Nice! Confirmed fixed :)
